\set ON_ERROR_STOP on

-- Operational FBS workflow. Every legal entity receives physically separate
-- tables in its own PostgreSQL schema.
BEGIN;

CREATE TABLE IF NOT EXISTS public.fbs_fulfillment_orders (
  order_id BIGINT PRIMARY KEY,
  order_uid TEXT NOT NULL DEFAULT '',
  supply_id TEXT,
  warehouse_id BIGINT,
  nm_id BIGINT NOT NULL,
  chrt_id BIGINT NOT NULL,
  vendor_code TEXT NOT NULL DEFAULT '',
  product_name TEXT NOT NULL DEFAULT '',
  size_name TEXT NOT NULL DEFAULT '',
  photo_url TEXT NOT NULL DEFAULT '',
  skus JSONB NOT NULL DEFAULT '[]'::jsonb,
  required_meta JSONB NOT NULL DEFAULT '[]'::jsonb,
  optional_meta JSONB NOT NULL DEFAULT '[]'::jsonb,
  supplier_status TEXT NOT NULL DEFAULT 'new',
  wb_status TEXT NOT NULL DEFAULT 'waiting',
  picked_at TIMESTAMPTZ,
  sticker_printed_at TIMESTAMPTZ,
  sticker_barcode TEXT NOT NULL DEFAULT '',
  packed_at TIMESTAMPTZ,
  metadata_checked_at TIMESTAMPTZ,
  metadata_decisions JSONB NOT NULL DEFAULT '[]'::jsonb,
  optional_meta_reviewed_at TIMESTAMPTZ,
  reshipment_required BOOLEAN NOT NULL DEFAULT FALSE,
  created_at_wb TIMESTAMPTZ,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  raw_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS fbs_fulfillment_orders_supply_idx
  ON public.fbs_fulfillment_orders (supply_id, supplier_status, created_at_wb);
CREATE INDEX IF NOT EXISTS fbs_fulfillment_orders_status_idx
  ON public.fbs_fulfillment_orders (supplier_status, wb_status, created_at_wb);

CREATE TABLE IF NOT EXISTS public.fbs_fulfillment_supplies (
  supply_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  delivery_mode TEXT NOT NULL DEFAULT 'warehouse'
    CHECK (delivery_mode IN ('warehouse', 'pvz')),
  destination_office_id BIGINT,
  destination_name TEXT NOT NULL DEFAULT '',
  done BOOLEAN NOT NULL DEFAULT FALSE,
  is_b2b BOOLEAN,
  cargo_type INTEGER,
  order_count INTEGER NOT NULL DEFAULT 0,
  boxes_count INTEGER NOT NULL DEFAULT 0,
  qr_printed_at TIMESTAMPTZ,
  created_at_wb TIMESTAMPTZ,
  closed_at_wb TIMESTAMPTZ,
  scan_at_wb TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  raw_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS fbs_fulfillment_supplies_open_idx
  ON public.fbs_fulfillment_supplies (done, created_at_wb DESC);

CREATE TABLE IF NOT EXISTS public.fbs_fulfillment_scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT,
  supply_id TEXT,
  scan_type TEXT NOT NULL,
  value_hash TEXT NOT NULL DEFAULT '',
  value_masked TEXT NOT NULL DEFAULT '',
  result TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS fbs_fulfillment_scans_created_idx
  ON public.fbs_fulfillment_scans (created_at DESC);

CREATE TABLE IF NOT EXISTS public.fbs_fulfillment_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT,
  supply_id TEXT,
  action TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ok',
  message TEXT NOT NULL DEFAULT '',
  details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS fbs_fulfillment_events_created_idx
  ON public.fbs_fulfillment_events (created_at DESC);

CREATE TABLE IF NOT EXISTS public.fbs_print_agents (
  agent_id TEXT PRIMARY KEY,
  name TEXT NOT NULL DEFAULT 'FBS print-agent',
  token_hash TEXT NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  printer_name TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'offline',
  last_error TEXT NOT NULL DEFAULT '',
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.fbs_print_jobs (
  job_id TEXT PRIMARY KEY,
  supply_id TEXT NOT NULL,
  group_key TEXT NOT NULL,
  nm_id BIGINT NOT NULL,
  chrt_id BIGINT NOT NULL,
  sku TEXT NOT NULL DEFAULT '',
  product_name TEXT NOT NULL DEFAULT '',
  size_name TEXT NOT NULL DEFAULT '',
  total_count INTEGER NOT NULL,
  printed_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued','printing','paused','completed','cancelled','error')),
  agent_id TEXT,
  last_error TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS fbs_print_jobs_supply_idx
  ON public.fbs_print_jobs (supply_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS fbs_print_jobs_active_group_idx
  ON public.fbs_print_jobs (supply_id, group_key)
  WHERE status IN ('queued','printing','paused');

CREATE TABLE IF NOT EXISTS public.fbs_print_job_items (
  job_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  order_id BIGINT NOT NULL,
  sticker_barcode TEXT NOT NULL DEFAULT '',
  sticker_file TEXT NOT NULL,
  sticker_format TEXT NOT NULL DEFAULT 'png',
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','printing','uncertain','printed')),
  lease_until TIMESTAMPTZ,
  printed_at TIMESTAMPTZ,
  PRIMARY KEY (job_id, position),
  UNIQUE (job_id, order_id)
);
ALTER TABLE public.fbs_print_job_items
  ADD COLUMN IF NOT EXISTS sticker_format TEXT NOT NULL DEFAULT 'png';
CREATE INDEX IF NOT EXISTS fbs_print_job_items_claim_idx
  ON public.fbs_print_job_items (status, lease_until, job_id, position);

DO $clone_existing$
DECLARE
  org RECORD;
  table_name TEXT;
  tenant_tables TEXT[] := ARRAY[
    'fbs_fulfillment_orders', 'fbs_fulfillment_supplies',
    'fbs_fulfillment_scans', 'fbs_fulfillment_events',
    'fbs_print_agents', 'fbs_print_jobs', 'fbs_print_job_items'
  ];
BEGIN
  FOR org IN SELECT id, data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
    IF org.data_schema <> format('organization_%s', org.id) THEN
      RAISE EXCEPTION 'Invalid schema % for organization %', org.data_schema, org.id;
    END IF;
    FOREACH table_name IN ARRAY tenant_tables LOOP
      EXECUTE format('CREATE TABLE IF NOT EXISTS %I.%I (LIKE public.%I INCLUDING ALL)',
        org.data_schema, table_name, table_name);
    END LOOP;
  END LOOP;
END
$clone_existing$;

DO $tenant_print_indexes$
DECLARE org RECORD;
BEGIN
  FOR org IN SELECT data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
    EXECUTE format('ALTER TABLE %I.fbs_print_job_items ADD COLUMN IF NOT EXISTS sticker_format TEXT NOT NULL DEFAULT ''png''', org.data_schema);
    EXECUTE format('CREATE UNIQUE INDEX IF NOT EXISTS fbs_print_jobs_active_group_idx ON %I.fbs_print_jobs (supply_id,group_key) WHERE status IN (''queued'',''printing'',''paused'')', org.data_schema);
  END LOOP;
END
$tenant_print_indexes$;

-- Extend provisioning for legal entities created after this release.
CREATE OR REPLACE FUNCTION public.mphub_provision_organization_schema(target_organization_id BIGINT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $provision$
DECLARE
  target_schema TEXT;
  table_name TEXT;
  tenant_tables TEXT[] := ARRAY[
    'advertising', 'buyout_rates', 'campaign_nm_map', 'cogs', 'cogs_history',
    'fbs_fulfillment_events', 'fbs_fulfillment_orders', 'fbs_fulfillment_scans', 'fbs_fulfillment_supplies',
    'fbs_marking_queue', 'fbs_print_agents', 'fbs_print_job_items', 'fbs_print_jobs',
    'fbs_stock_audit', 'fbs_stock_orders', 'fbs_stock_products', 'fbs_stock_warehouses',
    'orders', 'orders_funnel', 'paid_storage', 'product_overrides', 'realization',
    'realization_dedupe_backup_20260626', 'realization_report_meta', 'reports',
    'review_accounts', 'review_complaint_pauses', 'review_complaints',
    'review_stats', 'reviews', 'reviews_archive_sync_state', 'settings',
    'shipment_meta', 'shipment_orders', 'shipment_products', 'shipment_stock',
    'sync_status', 'tax_settings', 'user_settings', 'warehouse_measurements',
    'warehouse_ready_stock', 'warehouse_remains_volume', 'warehouse_sync_runs',
    'wb_accepted_supplies', 'wb_accepted_supply_contents', 'wb_cart_stock_jobs',
    'wb_cart_stock_snapshots', 'wb_supply_contents', 'wb_supply_report_documents',
    'wb_supply_snapshots', 'weekly_buyout_stats', 'weekly_import_status', 'weekly_rows'
  ];
BEGIN
  SELECT data_schema INTO target_schema FROM public.organizations WHERE id = target_organization_id;
  IF target_schema IS NULL THEN RAISE EXCEPTION 'Organization % does not exist', target_organization_id; END IF;
  IF target_organization_id = 1 AND target_schema = 'public' THEN RETURN target_schema; END IF;
  IF target_schema <> format('organization_%s', target_organization_id) THEN
    RAISE EXCEPTION 'Invalid schema % for organization %', target_schema, target_organization_id;
  END IF;
  EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target_schema);
  FOREACH table_name IN ARRAY tenant_tables LOOP
    IF to_regclass('public.' || table_name) IS NULL THEN
      RAISE EXCEPTION 'Source tenant table public.% does not exist', table_name;
    END IF;
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.%I (LIKE public.%I INCLUDING ALL)',
      target_schema, table_name, table_name);
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', target_schema);
  END IF;
  RETURN target_schema;
END
$provision$;

REVOKE ALL ON FUNCTION public.mphub_provision_organization_schema(BIGINT) FROM PUBLIC;

DO $grants$
DECLARE org RECORD;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_fulfillment_orders TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_fulfillment_supplies TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_fulfillment_scans TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_fulfillment_events TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_print_agents TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_print_jobs TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_print_job_items TO mphub_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mphub_app;
    GRANT EXECUTE ON FUNCTION public.mphub_provision_organization_schema(BIGINT) TO mphub_app;
    FOR org IN SELECT data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
      EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_app', org.data_schema);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO mphub_app', org.data_schema);
      EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', org.data_schema);
    END LOOP;
  END IF;
END
$grants$;

COMMIT;
