\set ON_ERROR_STOP on

-- Organization-isolated archive of already applied Honest Sign codes.
-- Raw Data Matrix values are encrypted by the application before insert and
-- are never returned by the API. Batch printing is added by the subsequent
-- 20260814-fbs-kiz-printing.sql migration.
BEGIN;

CREATE TABLE IF NOT EXISTS public.fbs_kiz_archive (
  archive_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identity_hash TEXT NOT NULL UNIQUE,
  code_hash TEXT NOT NULL UNIQUE,
  value_ciphertext TEXT NOT NULL,
  gtin TEXT NOT NULL,
  serial_tail TEXT NOT NULL,
  nm_id BIGINT NOT NULL,
  chrt_id BIGINT NOT NULL DEFAULT 0,
  vendor_code TEXT NOT NULL DEFAULT '',
  product_name TEXT NOT NULL DEFAULT '',
  size_name TEXT NOT NULL DEFAULT '',
  barcode TEXT NOT NULL,
  verification_status TEXT NOT NULL
    CHECK (verification_status IN ('format_verified','online_verified','error')),
  verification_source TEXT NOT NULL DEFAULT 'local',
  verification_message TEXT NOT NULL DEFAULT '',
  scan_count INTEGER NOT NULL DEFAULT 1 CHECK (scan_count > 0),
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_checked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS fbs_kiz_archive_product_idx
  ON public.fbs_kiz_archive (nm_id,barcode,archive_id DESC);
CREATE INDEX IF NOT EXISTS fbs_kiz_archive_status_idx
  ON public.fbs_kiz_archive (verification_status,archive_id DESC);

CREATE TABLE IF NOT EXISTS public.fbs_kiz_archive_events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archive_id BIGINT,
  event_type TEXT NOT NULL CHECK (event_type IN ('added','duplicate','error','checked')),
  code_hash TEXT NOT NULL,
  code_tail TEXT NOT NULL DEFAULT '',
  nm_id BIGINT,
  product_name TEXT NOT NULL DEFAULT '',
  size_name TEXT NOT NULL DEFAULT '',
  verification_status TEXT NOT NULL
    CHECK (verification_status IN ('format_verified','online_verified','error')),
  message TEXT NOT NULL DEFAULT '',
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS fbs_kiz_archive_events_recent_idx
  ON public.fbs_kiz_archive_events (event_id DESC);
CREATE INDEX IF NOT EXISTS fbs_kiz_archive_events_archive_idx
  ON public.fbs_kiz_archive_events (archive_id,event_id DESC);

DO $clone_existing$
DECLARE org RECORD;
BEGIN
  FOR org IN SELECT id,data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
    IF org.data_schema <> format('organization_%s', org.id) THEN
      RAISE EXCEPTION 'Invalid schema % for organization %', org.data_schema, org.id;
    END IF;
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.fbs_kiz_archive (LIKE public.fbs_kiz_archive INCLUDING ALL)',
      org.data_schema
    );
    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS fbs_kiz_archive_product_idx ON %I.fbs_kiz_archive (nm_id,barcode,archive_id DESC)',
      org.data_schema
    );
    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS fbs_kiz_archive_status_idx ON %I.fbs_kiz_archive (verification_status,archive_id DESC)',
      org.data_schema
    );
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.fbs_kiz_archive_events (LIKE public.fbs_kiz_archive_events INCLUDING ALL)',
      org.data_schema
    );
    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS fbs_kiz_archive_events_recent_idx ON %I.fbs_kiz_archive_events (event_id DESC)',
      org.data_schema
    );
    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS fbs_kiz_archive_events_archive_idx ON %I.fbs_kiz_archive_events (archive_id,event_id DESC)',
      org.data_schema
    );
  END LOOP;
END
$clone_existing$;

-- Keep future organization provisioning structurally complete.
CREATE OR REPLACE FUNCTION public.mphub_provision_organization_schema(target_organization_id BIGINT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $provision$
DECLARE
  target_schema TEXT;
  table_name TEXT;
  tenant_tables TEXT[] := ARRAY[
    'advertising', 'buyout_rates', 'campaign_nm_map', 'cogs', 'cogs_history',
    'fbs_fulfillment_events', 'fbs_fulfillment_orders', 'fbs_fulfillment_scans', 'fbs_fulfillment_supplies',
    'fbs_kiz_archive', 'fbs_kiz_archive_events', 'fbs_marking_queue',
    'fbs_print_agents', 'fbs_print_job_items', 'fbs_print_jobs',
    'fbs_stock_audit', 'fbs_stock_orders', 'fbs_stock_products', 'fbs_stock_warehouses',
    'orders', 'orders_funnel', 'paid_storage', 'product_overrides', 'realization',
    'realization_dedupe_backup_20260626', 'realization_report_meta', 'reports',
    'review_accounts', 'review_complaint_pauses', 'review_complaints',
    'review_stats', 'reviews', 'reviews_archive_sync_state', 'settings',
    'shipment_meta', 'shipment_orders', 'shipment_products', 'shipment_stock',
    'sync_status', 'tax_settings', 'user_settings', 'warehouse_measurements',
    'warehouse_ready_stock', 'warehouse_remains_volume', 'warehouse_sync_runs',
    'wb_accepted_supplies', 'wb_accepted_supply_contents', 'wb_cart_stock_jobs',
    'wb_cart_stock_snapshots', 'wb_supply_contents', 'wb_supply_report_documents',
    'wb_supply_snapshots', 'weekly_buyout_stats', 'weekly_import_status', 'weekly_rows'
  ];
BEGIN
  SELECT data_schema INTO target_schema FROM public.organizations WHERE id = target_organization_id;
  IF target_schema IS NULL THEN RAISE EXCEPTION 'Organization % does not exist', target_organization_id; END IF;
  IF target_organization_id = 1 AND target_schema = 'public' THEN RETURN target_schema; END IF;
  IF target_schema <> format('organization_%s', target_organization_id) THEN
    RAISE EXCEPTION 'Invalid schema % for organization %', target_schema, target_organization_id;
  END IF;
  EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target_schema);
  FOREACH table_name IN ARRAY tenant_tables LOOP
    IF to_regclass('public.' || table_name) IS NULL THEN
      RAISE EXCEPTION 'Source tenant table public.% does not exist', table_name;
    END IF;
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.%I (LIKE public.%I INCLUDING ALL)',
      target_schema, table_name, table_name);
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', target_schema);
  END IF;
  RETURN target_schema;
END
$provision$;

REVOKE ALL ON FUNCTION public.mphub_provision_organization_schema(BIGINT) FROM PUBLIC;

DO $grants$
DECLARE org RECORD;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_kiz_archive TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_kiz_archive_events TO mphub_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mphub_app;
    GRANT EXECUTE ON FUNCTION public.mphub_provision_organization_schema(BIGINT) TO mphub_app;
    FOR org IN SELECT data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
      EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_app', org.data_schema);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I.fbs_kiz_archive TO mphub_app', org.data_schema);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I.fbs_kiz_archive_events TO mphub_app', org.data_schema);
      EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', org.data_schema);
    END LOOP;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_readonly') THEN
    GRANT SELECT ON public.fbs_kiz_archive TO mphub_readonly;
    GRANT SELECT ON public.fbs_kiz_archive_events TO mphub_readonly;
    GRANT SELECT ON public.fbs_fulfillment_orders TO mphub_readonly;
    GRANT SELECT ON public.shipment_products TO mphub_readonly;
    FOR org IN SELECT data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
      EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_readonly', org.data_schema);
      EXECUTE format('GRANT SELECT ON %I.fbs_kiz_archive TO mphub_readonly', org.data_schema);
      EXECUTE format('GRANT SELECT ON %I.fbs_kiz_archive_events TO mphub_readonly', org.data_schema);
      EXECUTE format('GRANT SELECT ON %I.fbs_fulfillment_orders TO mphub_readonly', org.data_schema);
      EXECUTE format('GRANT SELECT ON %I.shipment_products TO mphub_readonly', org.data_schema);
    END LOOP;
  END IF;
END
$grants$;

COMMIT;
