\set ON_ERROR_STOP on

-- Durable per-organization queue for FBS Honest Sign uploads. The full code is
-- kept only while delivery to WB is pending and is erased immediately after a
-- successful PUT. Every tenant receives a physically separate table.
BEGIN;

CREATE TABLE IF NOT EXISTS public.fbs_marking_queue (
  queue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id BIGINT NOT NULL UNIQUE,
  order_id BIGINT NOT NULL,
  supply_id TEXT,
  value_hash TEXT NOT NULL,
  value_payload TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued','sending','sent','retry','verified','error')),
  attempts INTEGER NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lease_until TIMESTAMPTZ,
  last_error TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sent_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS fbs_marking_queue_claim_idx
  ON public.fbs_marking_queue (status, available_at, queue_id);
CREATE INDEX IF NOT EXISTS fbs_marking_queue_order_idx
  ON public.fbs_marking_queue (order_id, queue_id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS fbs_marking_queue_active_order_idx
  ON public.fbs_marking_queue (order_id)
  WHERE status IN ('queued','sending','sent','retry');

DO $clone_existing$
DECLARE org RECORD;
BEGIN
  FOR org IN SELECT id, data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
    IF org.data_schema <> format('organization_%s', org.id) THEN
      RAISE EXCEPTION 'Invalid schema % for organization %', org.data_schema, org.id;
    END IF;
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.fbs_marking_queue (LIKE public.fbs_marking_queue INCLUDING ALL)',
      org.data_schema
    );
    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS fbs_marking_queue_claim_idx ON %I.fbs_marking_queue (status,available_at,queue_id)',
      org.data_schema
    );
    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS fbs_marking_queue_order_idx ON %I.fbs_marking_queue (order_id,queue_id DESC)',
      org.data_schema
    );
    EXECUTE format(
      'CREATE UNIQUE INDEX IF NOT EXISTS fbs_marking_queue_active_order_idx ON %I.fbs_marking_queue (order_id) WHERE status IN (''queued'',''sending'',''sent'',''retry'')',
      org.data_schema
    );
  END LOOP;
END
$clone_existing$;

-- Keep provisioning complete for legal entities created after this release.
CREATE OR REPLACE FUNCTION public.mphub_provision_organization_schema(target_organization_id BIGINT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $provision$
DECLARE
  target_schema TEXT;
  table_name TEXT;
  tenant_tables TEXT[] := ARRAY[
    'advertising', 'buyout_rates', 'campaign_nm_map', 'cogs', 'cogs_history',
    'fbs_fulfillment_events', 'fbs_fulfillment_orders', 'fbs_fulfillment_scans', 'fbs_fulfillment_supplies',
    'fbs_marking_queue', 'fbs_print_agents', 'fbs_print_job_items', 'fbs_print_jobs',
    'fbs_stock_audit', 'fbs_stock_orders', 'fbs_stock_products', 'fbs_stock_warehouses',
    'orders', 'orders_funnel', 'paid_storage', 'product_overrides', 'realization',
    'realization_dedupe_backup_20260626', 'realization_report_meta', 'reports',
    'review_accounts', 'review_complaint_pauses', 'review_complaints',
    'review_stats', 'reviews', 'reviews_archive_sync_state', 'settings',
    'shipment_meta', 'shipment_orders', 'shipment_products', 'shipment_stock',
    'sync_status', 'tax_settings', 'user_settings', 'warehouse_measurements',
    'warehouse_ready_stock', 'warehouse_remains_volume', 'warehouse_sync_runs',
    'wb_accepted_supplies', 'wb_accepted_supply_contents', 'wb_cart_stock_jobs',
    'wb_cart_stock_snapshots', 'wb_supply_contents', 'wb_supply_report_documents',
    'wb_supply_snapshots', 'weekly_buyout_stats', 'weekly_import_status', 'weekly_rows'
  ];
BEGIN
  SELECT data_schema INTO target_schema FROM public.organizations WHERE id = target_organization_id;
  IF target_schema IS NULL THEN RAISE EXCEPTION 'Organization % does not exist', target_organization_id; END IF;
  IF target_organization_id = 1 AND target_schema = 'public' THEN RETURN target_schema; END IF;
  IF target_schema <> format('organization_%s', target_organization_id) THEN
    RAISE EXCEPTION 'Invalid schema % for organization %', target_schema, target_organization_id;
  END IF;
  EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target_schema);
  FOREACH table_name IN ARRAY tenant_tables LOOP
    IF to_regclass('public.' || table_name) IS NULL THEN
      RAISE EXCEPTION 'Source tenant table public.% does not exist', table_name;
    END IF;
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.%I (LIKE public.%I INCLUDING ALL)',
      target_schema, table_name, table_name);
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', target_schema);
  END IF;
  RETURN target_schema;
END
$provision$;

REVOKE ALL ON FUNCTION public.mphub_provision_organization_schema(BIGINT) FROM PUBLIC;

DO $grants$
DECLARE org RECORD;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_marking_queue TO mphub_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mphub_app;
    FOR org IN SELECT data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I.fbs_marking_queue TO mphub_app', org.data_schema);
      EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', org.data_schema);
    END LOOP;
  END IF;
END
$grants$;

COMMIT;
