\set ON_ERROR_STOP on

-- Isolated FBS stock manager state. Business tables live in every tenant
-- schema; no stock, order, or sync state is shared between legal entities.
BEGIN;

CREATE TABLE IF NOT EXISTS public.fbs_stock_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_id BIGINT NOT NULL,
  chrt_id BIGINT NOT NULL,
  vendor_code TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  size_name TEXT NOT NULL DEFAULT '',
  physical_quantity INTEGER NOT NULL DEFAULT 0 CHECK (physical_quantity >= 0),
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  baseline_at TIMESTAMPTZ,
  last_new_orders_at TIMESTAMPTZ,
  last_history_at TIMESTAMPTZ,
  last_sync_at TIMESTAMPTZ,
  last_success_at TIMESTAMPTZ,
  last_error TEXT,
  sync_lock_token TEXT,
  sync_lock_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (nm_id, chrt_id)
);

CREATE TABLE IF NOT EXISTS public.fbs_stock_warehouses (
  product_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  warehouse_name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  target_quantity INTEGER NOT NULL DEFAULT 0 CHECK (target_quantity >= 0),
  confirmed_quantity INTEGER CHECK (confirmed_quantity >= 0),
  last_checked_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (product_id, warehouse_id)
);

CREATE INDEX IF NOT EXISTS fbs_stock_warehouses_enabled_idx
  ON public.fbs_stock_warehouses (product_id, enabled, warehouse_id);

CREATE TABLE IF NOT EXISTS public.fbs_stock_orders (
  order_id BIGINT PRIMARY KEY,
  product_id BIGINT NOT NULL,
  nm_id BIGINT NOT NULL,
  chrt_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  created_at_wb TIMESTAMPTZ NOT NULL,
  supplier_status TEXT,
  wb_status TEXT,
  accounting_state TEXT NOT NULL DEFAULT 'pending'
    CHECK (accounting_state IN ('pending', 'counted', 'released', 'baseline', 'external_warehouse')),
  counted_at TIMESTAMPTZ,
  released_at TIMESTAMPTZ,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  raw_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS fbs_stock_orders_product_created_idx
  ON public.fbs_stock_orders (product_id, created_at_wb DESC);

CREATE INDEX IF NOT EXISTS fbs_stock_orders_status_idx
  ON public.fbs_stock_orders (product_id, accounting_state, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.fbs_stock_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT,
  order_id BIGINT,
  action TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ok',
  warehouse_from_id BIGINT,
  warehouse_to_id BIGINT,
  quantity INTEGER,
  message TEXT NOT NULL DEFAULT '',
  details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS fbs_stock_audit_created_idx
  ON public.fbs_stock_audit (created_at DESC);

-- Clone the new tables into all existing non-primary tenant schemas.
DO $clone_existing$
DECLARE
  org RECORD;
  table_name TEXT;
  tenant_tables TEXT[] := ARRAY[
    'fbs_stock_products',
    'fbs_stock_warehouses',
    'fbs_stock_orders',
    'fbs_stock_audit'
  ];
BEGIN
  FOR org IN
    SELECT id, data_schema
    FROM public.organizations
    WHERE data_schema <> 'public'
  LOOP
    IF org.data_schema <> format('organization_%s', org.id) THEN
      RAISE EXCEPTION 'Invalid schema % for organization %', org.data_schema, org.id;
    END IF;
    FOREACH table_name IN ARRAY tenant_tables LOOP
      EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I.%I (LIKE public.%I INCLUDING ALL)',
        org.data_schema,
        table_name,
        table_name
      );
    END LOOP;
  END LOOP;
END
$clone_existing$;

-- Keep future organization provisioning in sync with the new module.
CREATE OR REPLACE FUNCTION public.mphub_provision_organization_schema(target_organization_id BIGINT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $provision$
DECLARE
  target_schema TEXT;
  table_name TEXT;
  tenant_tables TEXT[] := ARRAY[
    'advertising', 'buyout_rates', 'campaign_nm_map', 'cogs', 'cogs_history',
    'fbs_stock_audit', 'fbs_stock_orders', 'fbs_stock_products', 'fbs_stock_warehouses',
    'orders', 'orders_funnel', 'paid_storage', 'product_overrides', 'realization',
    'realization_dedupe_backup_20260626', 'realization_report_meta', 'reports',
    'review_accounts', 'review_complaint_pauses', 'review_complaints',
    'review_stats', 'reviews', 'reviews_archive_sync_state', 'settings',
    'shipment_meta', 'shipment_orders', 'shipment_products', 'shipment_stock',
    'sync_status', 'tax_settings', 'user_settings', 'warehouse_measurements',
    'warehouse_ready_stock', 'warehouse_remains_volume', 'warehouse_sync_runs',
    'wb_accepted_supplies', 'wb_accepted_supply_contents', 'wb_cart_stock_jobs',
    'wb_cart_stock_snapshots', 'wb_supply_contents', 'wb_supply_report_documents',
    'wb_supply_snapshots', 'weekly_buyout_stats', 'weekly_import_status', 'weekly_rows'
  ];
BEGIN
  SELECT data_schema INTO target_schema
  FROM public.organizations
  WHERE id = target_organization_id;

  IF target_schema IS NULL THEN
    RAISE EXCEPTION 'Organization % does not exist', target_organization_id;
  END IF;
  IF target_organization_id = 1 AND target_schema = 'public' THEN
    RETURN target_schema;
  END IF;
  IF target_schema <> format('organization_%s', target_organization_id) THEN
    RAISE EXCEPTION 'Invalid schema % for organization %', target_schema, target_organization_id;
  END IF;

  EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target_schema);
  FOREACH table_name IN ARRAY tenant_tables LOOP
    IF to_regclass('public.' || table_name) IS NULL THEN
      RAISE EXCEPTION 'Source tenant table public.% does not exist', table_name;
    END IF;
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.%I (LIKE public.%I INCLUDING ALL)',
      target_schema, table_name, table_name
    );
  END LOOP;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', target_schema);
  END IF;
  RETURN target_schema;
END
$provision$;

REVOKE ALL ON FUNCTION public.mphub_provision_organization_schema(BIGINT) FROM PUBLIC;

DO $grants$
DECLARE
  org RECORD;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_stock_products TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_stock_warehouses TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_stock_orders TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_stock_audit TO mphub_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mphub_app;
    GRANT EXECUTE ON FUNCTION public.mphub_provision_organization_schema(BIGINT) TO mphub_app;
    FOR org IN SELECT data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
      EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_app', org.data_schema);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO mphub_app', org.data_schema);
      EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', org.data_schema);
    END LOOP;
  END IF;
END
$grants$;

COMMIT;
