\set ON_ERROR_STOP on

-- Additive, tenant-isolated FBS supply archive. Operational assembly fields
-- stay in the existing tables; this migration only adds immutable identifiers,
-- observed status history and sale/return events used by the archive UI.
BEGIN;

ALTER TABLE public.fbs_fulfillment_orders
  ADD COLUMN IF NOT EXISTS rid TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sticker_id BIGINT,
  ADD COLUMN IF NOT EXISTS status_synced_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS archive_source TEXT NOT NULL DEFAULT 'live';

ALTER TABLE public.fbs_fulfillment_supplies
  ADD COLUMN IF NOT EXISTS verified_order_count INTEGER,
  ADD COLUMN IF NOT EXISTS composition_checked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS archive_synced_at TIMESTAMPTZ;

UPDATE public.fbs_fulfillment_orders
SET rid=COALESCE(NULLIF(raw_json->>'rid',''), rid),
    sticker_id=COALESCE(sticker_id, CASE WHEN COALESCE(raw_json->>'stickerId','') ~ '^[0-9]+$' THEN (raw_json->>'stickerId')::BIGINT END)
WHERE (rid='' AND COALESCE(raw_json->>'rid','')<>'')
   OR (sticker_id IS NULL AND COALESCE(raw_json->>'stickerId','') ~ '^[0-9]+$');

CREATE INDEX IF NOT EXISTS fbs_fulfillment_orders_rid_idx
  ON public.fbs_fulfillment_orders (rid) WHERE rid<>'';
CREATE INDEX IF NOT EXISTS fbs_fulfillment_orders_archive_idx
  ON public.fbs_fulfillment_orders (created_at_wb DESC, supply_id, wb_status);

CREATE TABLE IF NOT EXISTS public.fbs_order_status_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  supplier_status TEXT NOT NULL,
  wb_status TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'live',
  first_observed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_observed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  observations INTEGER NOT NULL DEFAULT 1,
  raw_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (order_id, supplier_status, wb_status)
);
CREATE INDEX IF NOT EXISTS fbs_order_status_events_order_idx
  ON public.fbs_order_status_events (order_id, first_observed_at);

CREATE TABLE IF NOT EXISTS public.fbs_sales_events (
  event_id TEXT PRIMARY KEY,
  order_id BIGINT,
  rid TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('sale','return')),
  event_at TIMESTAMPTZ,
  last_change_at TIMESTAMPTZ,
  source TEXT NOT NULL,
  raw_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS fbs_sales_events_rid_idx
  ON public.fbs_sales_events (rid, event_type, event_at DESC);
CREATE INDEX IF NOT EXISTS fbs_sales_events_order_idx
  ON public.fbs_sales_events (order_id, event_type, event_at DESC);

CREATE TABLE IF NOT EXISTS public.fbs_archive_sync_state (
  source TEXT PRIMARY KEY,
  cursor_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_success_at TIMESTAMPTZ,
  last_error TEXT NOT NULL DEFAULT '',
  last_error_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $tenant_archive$
DECLARE
  org RECORD;
BEGIN
  FOR org IN SELECT data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
    IF org.data_schema !~ '^organization_[0-9]+$' THEN
      RAISE EXCEPTION 'Invalid organization schema %', org.data_schema;
    END IF;

    EXECUTE format('ALTER TABLE %I.fbs_fulfillment_orders ADD COLUMN IF NOT EXISTS rid TEXT NOT NULL DEFAULT ''''', org.data_schema);
    EXECUTE format('ALTER TABLE %I.fbs_fulfillment_orders ADD COLUMN IF NOT EXISTS sticker_id BIGINT', org.data_schema);
    EXECUTE format('ALTER TABLE %I.fbs_fulfillment_orders ADD COLUMN IF NOT EXISTS status_synced_at TIMESTAMPTZ', org.data_schema);
    EXECUTE format('ALTER TABLE %I.fbs_fulfillment_orders ADD COLUMN IF NOT EXISTS archive_source TEXT NOT NULL DEFAULT ''live''', org.data_schema);
    EXECUTE format('ALTER TABLE %I.fbs_fulfillment_supplies ADD COLUMN IF NOT EXISTS verified_order_count INTEGER', org.data_schema);
    EXECUTE format('ALTER TABLE %I.fbs_fulfillment_supplies ADD COLUMN IF NOT EXISTS composition_checked_at TIMESTAMPTZ', org.data_schema);
    EXECUTE format('ALTER TABLE %I.fbs_fulfillment_supplies ADD COLUMN IF NOT EXISTS archive_synced_at TIMESTAMPTZ', org.data_schema);

    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.fbs_order_status_events (LIKE public.fbs_order_status_events INCLUDING ALL)', org.data_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.fbs_sales_events (LIKE public.fbs_sales_events INCLUDING ALL)', org.data_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.fbs_archive_sync_state (LIKE public.fbs_archive_sync_state INCLUDING ALL)', org.data_schema);

    EXECUTE format($sql$
      UPDATE %I.fbs_fulfillment_orders
      SET rid=COALESCE(NULLIF(raw_json->>'rid',''), rid),
          sticker_id=COALESCE(sticker_id, CASE WHEN COALESCE(raw_json->>'stickerId','') ~ '^[0-9]+$' THEN (raw_json->>'stickerId')::BIGINT END)
      WHERE (rid='' AND COALESCE(raw_json->>'rid','')<>'')
         OR (sticker_id IS NULL AND COALESCE(raw_json->>'stickerId','') ~ '^[0-9]+$')
    $sql$, org.data_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS fbs_fulfillment_orders_rid_idx ON %I.fbs_fulfillment_orders (rid) WHERE rid<>''''', org.data_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS fbs_fulfillment_orders_archive_idx ON %I.fbs_fulfillment_orders (created_at_wb DESC,supply_id,wb_status)', org.data_schema);
  END LOOP;
END
$tenant_archive$;

-- Keep future legal entities structurally identical to the existing ones.
CREATE OR REPLACE FUNCTION public.mphub_provision_organization_schema(target_organization_id BIGINT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $provision$
DECLARE
  target_schema TEXT;
  table_name TEXT;
  tenant_tables TEXT[] := ARRAY[
    'advertising', 'buyout_rates', 'campaign_nm_map', 'cogs', 'cogs_history',
    'fbs_archive_sync_state', 'fbs_fulfillment_events', 'fbs_fulfillment_orders',
    'fbs_fulfillment_scans', 'fbs_fulfillment_supplies', 'fbs_kiz_archive',
    'fbs_kiz_archive_events', 'fbs_kiz_gtin_mappings', 'fbs_marking_queue',
    'fbs_order_status_events', 'fbs_print_agents', 'fbs_print_job_items',
    'fbs_print_jobs', 'fbs_sales_events', 'fbs_stock_audit', 'fbs_stock_orders',
    'fbs_stock_products', 'fbs_stock_warehouses', 'orders', 'orders_funnel',
    'paid_storage', 'product_overrides', 'realization',
    'realization_dedupe_backup_20260626', 'realization_report_meta', 'reports',
    'review_accounts', 'review_complaint_pauses', 'review_complaints',
    'review_stats', 'reviews', 'reviews_archive_sync_state', 'settings',
    'shipment_meta', 'shipment_orders', 'shipment_products', 'shipment_stock',
    'sync_status', 'tax_settings', 'user_settings', 'warehouse_measurements',
    'warehouse_ready_stock', 'warehouse_remains_volume', 'warehouse_sync_runs',
    'wb_accepted_supplies', 'wb_accepted_supply_contents', 'wb_cart_stock_jobs',
    'wb_cart_stock_snapshots', 'wb_supply_contents', 'wb_supply_report_documents',
    'wb_supply_snapshots', 'weekly_buyout_stats', 'weekly_import_status', 'weekly_rows'
  ];
BEGIN
  SELECT data_schema INTO target_schema FROM public.organizations WHERE id = target_organization_id;
  IF target_schema IS NULL THEN RAISE EXCEPTION 'Organization % does not exist', target_organization_id; END IF;
  IF target_organization_id = 1 AND target_schema = 'public' THEN RETURN target_schema; END IF;
  IF target_schema <> format('organization_%s', target_organization_id) THEN
    RAISE EXCEPTION 'Invalid schema % for organization %', target_schema, target_organization_id;
  END IF;
  EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target_schema);
  FOREACH table_name IN ARRAY tenant_tables LOOP
    IF to_regclass('public.' || table_name) IS NULL THEN
      RAISE EXCEPTION 'Source tenant table public.% does not exist', table_name;
    END IF;
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.%I (LIKE public.%I INCLUDING ALL)', target_schema, table_name, table_name);
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO mphub_app', target_schema);
    EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', target_schema);
  END IF;
  RETURN target_schema;
END
$provision$;

REVOKE ALL ON FUNCTION public.mphub_provision_organization_schema(BIGINT) FROM PUBLIC;

DO $archive_grants$
DECLARE org RECORD;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_order_status_events TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_sales_events TO mphub_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.fbs_archive_sync_state TO mphub_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mphub_app;
    GRANT EXECUTE ON FUNCTION public.mphub_provision_organization_schema(BIGINT) TO mphub_app;
    FOR org IN SELECT data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
      EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON %I.fbs_order_status_events TO mphub_app', org.data_schema);
      EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON %I.fbs_sales_events TO mphub_app', org.data_schema);
      EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON %I.fbs_archive_sync_state TO mphub_app', org.data_schema);
      EXECUTE format('GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA %I TO mphub_app', org.data_schema);
    END LOOP;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mphub_readonly') THEN
    GRANT SELECT ON public.fbs_order_status_events TO mphub_readonly;
    GRANT SELECT ON public.fbs_sales_events TO mphub_readonly;
    GRANT SELECT ON public.fbs_archive_sync_state TO mphub_readonly;
    FOR org IN SELECT data_schema FROM public.organizations WHERE data_schema <> 'public' LOOP
      EXECUTE format('GRANT USAGE ON SCHEMA %I TO mphub_readonly', org.data_schema);
      EXECUTE format('GRANT SELECT ON %I.fbs_order_status_events TO mphub_readonly', org.data_schema);
      EXECUTE format('GRANT SELECT ON %I.fbs_sales_events TO mphub_readonly', org.data_schema);
      EXECUTE format('GRANT SELECT ON %I.fbs_archive_sync_state TO mphub_readonly', org.data_schema);
    END LOOP;
  END IF;
END
$archive_grants$;

COMMIT;
